### ISSUE TITLE
Add marginal density/histogram layers

### ISSUE THREAD

**Issue by mikejiang** [RGLab/ggcyto#10]
Sometime it will be helpful to see the `1d` density on either dimension along with  `geom_hex` plot to evaluate or investigate if the gates are placed at the appropriate locations. 
[ggExtra](https://github.com/daattali/ggExtra) nicely offers this feature by post-processing `ggtable`

``` r
p <- autoplot(gs, c("CD4","CD8")) + ggcyto_par_set(limits = "data")
p <- p + facet_null()
p <- as.ggplot(p)
ggMarginal(p)
```

![image](https://cloud.githubusercontent.com/assets/1385649/17074052/d002606e-502b-11e6-81f5-d5335707b7c5.png)
However it only works for the single panel and doesn't seem to be interested in supporting the `multi-panel` version (daattali/ggExtra#28). 

And `ggplot2`'s [geom_rug](http://docs.ggplot2.org/current/geom_rug.html) seems to be a more promising direction to go, We may be able to modify/extend it to `density/histogram`.

**Comment by mikejiang** [comment]
It turns out to be very difficult to implement a new `geom` by adding the `density grobs` through `draw_group` or `draw_panel` function since it shares the same `panel`(or `viewport`) with the `hex` layer, the scale of which will be too large for the `density layer` to be visible.

**Comment by mikejiang** [comment]
By fiddling with `gtable`, I am able to inject the extra `density` grobs into each `panel`
![image](https://cloud.githubusercontent.com/assets/1385649/17159553/f23e2d14-5352-11e6-8962-623f0c15a6ac.png)
However the original plot gets shifted due to the modification of the panels. I will have to fix that.

**Comment by raphg** [comment]
Personally, I don't think we want to do this. It goes a bit against the principle of ggplot as you're trying to add two plot types that are sort of incompatible. I think this would need to be done manually using cowplot.

**Comment by LicanMartinez** [comment]
Would you mind to share the code to generate that last faceted-marginalized plot?

**Comment by mikejiang** [comment]
Unfortunately I did not keep that code since this feature never got traction.
