### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by koljaschleich** [RGLab/ggcyto#11]
Hi,

I have problems installing ggcyto in R 3.2.3/Bioconductor 3.2 on a Mac running OSX El Capitan. Using biocLite("ggcyto") gives a message that it's not available for my version. So I tried to go the manual way. First I ran into version dependency issue with ncdfFlow (had 2.16.1, needed >= 2.17.1) and afterwards flowWorkspace (had 3.16.16, needed >= 3.17.24). I could then install both packages by manually downloading the mac packages (2.18.0 & 3.18.10) using install.packages("/src/of/file")

I then tried to install ggcyto manually the same way (1.0.6), which also worked. When I try to load the package, however, I get the error that  flowJo_biexp_trans is not exported from flowWorkspace!

Any help would be appreciated.

Regards,
Kolja

**Comment by gfinak** [comment]
flowWorkspace version 3.19.24, the latest on Bioconductor devel, as well as 3.18.10, the latest on release, both export this function. Which version do you have installed?

You may want to consider updating your R and Bioconductor and just let it handle the dependencies for you.

**Comment by koljaschleich** [comment]
Thanks for the prompt reply. Upgrading R and Bioconductor solved the issue
