### ISSUE TITLE
Autoplot error with flowFrame object

### ISSUE THREAD

**Issue by R-ag** [RGLab/ggcyto#17]
Hello,
 I am attempting to utilize flowCore and ggcyto to analyze some FCS data. I have been moving through the examples found in https://www.bioconductor.org/packages/devel/bioc/vignettes/flowCore/inst/doc/HowTo-flowCore.pdf and when I get to using the autoplot function I get the following error "Error: Objects of type flowFrame not supported by autoplot." I have checked the reference manual and am unable to find a solution. Is there a conversion of the read in FCS file that needs to happen?

**Comment by mikejiang** [comment]
looks like you didn't load the `ggcyto` library
