### ISSUE TITLE
Inconsistent behaviour of geom_gate and geom_stats

### ISSUE THREAD

**Issue by sellth** [RGLab/ggcyto#20]
When using ggcyto to plot a flowSet, geom_gate accepts a single filter object as an input and plots it across all samples without any trouble. Yet geom_stats cannot parse that gate data and returns a non-descriptive error message.

```
firstGate <- rectangleGate("SSC-A" = c(0, 5e6), "FSC-A" = c(0, 2e6))
p <- ggcyto(flowSet, aes(`FSC-A`, `SSC-A`)) + 
  geom_point(size = 0.1) + 
  geom_gate(firstGate)
p + geom_stats()

> Error in `[.data.table`(df, , c(markers, ".rownames"), with = FALSE) : 
  column(s) not found: .rownames
```
This behaviour can be rescued by creating a filterList (as described in the documentation) and passing it either to geom_gate or geom_stats.

```
firstGates <- sapply(sampleNames(flowSet), function(x) firstGate)
p + geom_stats(firstGates)
```
Maybe you could add a nice error message for this case, so other poor souls like me, who only read the docs after there is a problem, get put on the right track. Had a really hard time finding out what's wrong.

**Comment by mikejiang** [comment]
I've pushed the fix. Thanks for your feedback!
