### ISSUE TITLE
stacked histograms with ggjoy

### ISSUE THREAD

**Issue by mikejiang** [RGLab/ggcyto#21]
> Greg Finak [7:48 AM] 
> https://simplystatistics.org/2017/07/13/the-joy-of-no-more-violin-plots/
> An alternative to violin plots. Useful in ggcyto to make the stacked histograms that we had in flowviz.

**Comment by mikejiang** [comment]
It is pretty straight forward to do it 
```r
data(GvHD)
fs <- GvHD[subset(pData(GvHD), Patient %in%5:7 & Visit %in% c(5:6))[["name"]]]
# 1d histogram/densityplot
p <- ggcyto(fs, aes(x = `FSC-H`))
p + geom_joy(aes(y = name)) + facet_null()
```
![image](https://user-images.githubusercontent.com/1385649/28225051-1ba1dee6-6886-11e7-8864-b3b90317970d.png)

**Comment by mikejiang** [comment]
@gfinak , Do you want an easy wrapper (e.g. `geom_density_stack` ) to further simplify it?

**Comment by gfinak** [comment]
No I don't think that's necessary.

**Comment by mikejiang** [comment]
ok, I will just add the examples to the vignette and man page.
