### ISSUE TITLE
ggcyto:  Pass aes column names by variable

### ISSUE THREAD

**Issue by silpasuthram** [RGLab/ggcyto#22]
Hi, I am using ggcyto to plot CD8 vs CD4.  However, instead of explicitly defining the column names for aes, I want to define them using variables.  I tried the following 
p = ggcyto(gs,aes(x=get(cols1),y=get(cols2)),subset=getNodes(gs)[3])
            p=p+geom_hex()+geom_gate(getNodes(gs)[4])+geom_stats()
            p=p+facet_grid(Row~Col)
            plot(p) 

However, I get the following error:
Error: j (the 2nd argument inside [...]) is a single symbol but column name 'name' is not found. Perhaps you intended DT[,..name] or DT[,name,with=FALSE]. This difference to data.frame is deliberate and explained in FAQ 1.1.

The same code works if I explicitly specify the column names like below:
 p = ggcyto(gs,aes(x=CD8,y=CD4,subset=getNodes(gs)[3])
            p=p+geom_hex()+geom_gate(getNodes(gs)[4])+geom_stats()
            p=p+facet_grid(Row~Col)
            plot(p) 

Hope you can help?
Thanks

**Comment by mikejiang** [comment]
use `aes_string(col1, cos2)`
P.S. This is rather a `ggplot` question

**Comment by silpasuthram** [comment]
I tried that already and it doesn't work and gives the same issue

**Comment by mikejiang** [comment]
it works for me
```r
 dataDir <- system.file("extdata",package="flowWorkspaceData")
> gs <- load_gs(list.files(dataDir, pattern = "gs_manual",full = TRUE))
> col1 <- "CD4"
> col2 <- "CD8"
> ggcyto(gs, aes_string(col1, col2), subset = "CD3+") + geom_hex() + geom_gate("CD4")
```
You also need to use `facet_grid` in a proper way if the formula contains variable, again it is `ggplot` question, see `?facet_grid` for the help.

**Comment by mikejiang** [comment]
You need back ticks for the colnames of the flow data has sepcial characters `-`, e.g.
```r
col1="`Comp-FITC-A`"
```
Again, this is not `ggcyto` specific issue and you will have error even if you do it on the data.table with `ggplot` (the error message may be reported differently)

**Comment by silpasuthram** [comment]
Thank you.  That works!
