### ISSUE TITLE
axis_y_inverse_trans when arranging images with arrangeGrob()

### ISSUE THREAD

**Issue by arnaudcol** [RGLab/ggcyto#23]
When I display the graph below the axes do the inverse transformation
p <- ggcyto(gs[[1]],aes(x="FITC-A",y="APC-A"),subset="TCRab+")+
    geom_hex(bins=512,show.legend=F)+
    axis_x_inverse_trans()+
    axis_y_inverse_trans()+
    geom_gate()+
    geom_stats(label.padding=unit(0.2,"lines"),alpha=0.5,size=plot_size)
![rplot01](https://user-images.githubusercontent.com/15161284/29543190-3421a5ce-8694-11e7-85da-7bdec001c28c.png)

When i run the code below
  g1 <- arrangeGrob(p,p1,p2,p3,p4,p5,p6,p7,p8,ncol=5)
  ggsave(paste(foldername,"/Images/",substr(FCSFiles[i],1,nchar(FCSFiles[i])-4),"_Overlay.png",sep=""),plot=g1,width=11,height=5,units="in",device="png")

The transformation is gone
![adi17-057d9_a4_a04_overlay](https://user-images.githubusercontent.com/15161284/29543205-4b957384-8694-11e7-8c20-f85481968ceb.png)

**Comment by gfinak** [comment]
Call `p = ggcyto::as.ggplot(p)` on your plot objects, then follow with `arrangeGrob`

**Comment by arnaudcol** [comment]
That worked perfectly thanks!
