### ISSUE TITLE
stacked densities

### ISSUE THREAD

**Issue by mikejiang** [RGLab/ggcyto#25]
On 12/01/2017 12:10 PM, Mehrnoush Malek wrote:
> That I can do, but how can I add the gates to stacked densities? 
> It seems that when facet is null, then all thresholds would be added as a line to all densities. IS there any other way to do it?
>
> Mehrnoush 
> ________________________________________
> From: Mike <wjiang2@fhcrc.org>
> Sent: Friday, December 1, 2017 10:30
> To: Mehrnoush Malek
> Subject: Re: Help regarding flowViz
>
> I don't think you can facet by channels unless you transform the data
> from wide to long format, i.e. collapsing multiple channel columns into
> single column.
>
> The only thing you can do is to plot one channel at a time and
> grid.arrange them afterwards.
>
>
> On 11/30/2017 04:46 PM, Mehrnoush Malek wrote:
>> Thanks for your quick response! I'd actually like to have facets for different channels and then stacked density of samples on each, and different abline for each density.
>>
>> Mehrnoush
>> ________________________________________
>> From: Mike <wjiang2@fhcrc.org>
>> Sent: Thursday, November 30, 2017 16:17
>> To: Mehrnoush Malek
>> Subject: Re: Help regarding flowViz
>>
>> With `ggcyto`, it is straightfoward to do so through `geom_gate` see
>> https://urldefense.proofpoint.com/v2/url?u=https-3A__bioconductor.org_packages_release_bioc_vignettes_ggcyto_inst_doc_ggcyto.flowSet.html&d=DwIFAw&c=eRAMFD45gAfqt84VtBcfhQ&r=3im95Xp69FwgNjKVW2VYlLNIg6dze5_5h2nnIS_b2xo&m=TtftCxvOntHM_KkljoriuE72LFJ19oImhwCyGPAr9ug&s=3RcRhwl732wF15AcwRIPwLVJ6iup_LJUcgpsMt21sH8&e=
>>
>>
>> On 11/30/2017 04:09 PM, Mehrnoush Malek wrote:
>>> Hi Mike,
>>>
>>>
>>> Hope you're doing well. I just wanted to see if you know how to add vertical lines to densityplot.
>>>
>>> The refline doesn't seem to work multiple panels. If there's no easy way around it, I might just write my on function.
>>>
>>>
>>>
>>> Cheers,
>>>
>>> Mehrnoush
>

**Comment by mehrnoushmalek** [comment]
Thanks, I created my own costum function for what I needed.
