### ISSUE TITLE
Axes values change while plotting

### ISSUE THREAD

**Issue by JC203** [RGLab/ggcyto#29]
I noticed that the values on my axes change when I plot with ggcyto.
Using plotGate() from flowWorkspace gives me normal logarithmic values but when I use getData() I get these values

`getData(gs[[4]], "Lin-7AAD-")`
```
flowFrame object '59b9cdd3-2329-4dfd-b048-4283605a4f85'
with 41316 cells and 14 observables:
              name desc        range      minRange     maxRange
$P1          FSC-A <NA> 262143.00000  0.000000e+00 262143.00000
$P2          FSC-H <NA> 262143.00000  0.000000e+00 262143.00000
$P3          FSC-W <NA> 262143.00000  0.000000e+00 262143.00000
$P4          SSC-A <NA> 262254.00000 -1.110000e+02 262143.00000
$P5          SSC-H <NA> 262143.00000  0.000000e+00 262143.00000
$P6          SSC-W <NA> 262143.00000  0.000000e+00 262143.00000
$P7    Comp-FITC-A <NA>    205.64796  5.126667e+01    256.91464
$P8     Comp-APC-A <NA>    206.21435  5.070029e+01    256.91464
$P9   Comp-BV421-A <NA>    206.21435  5.070029e+01    256.91464
$P10      BUV395-A <NA>    204.08298  5.283166e+01    256.91464
$P11      BYG584-A <NA>    206.21435  5.070029e+01    256.91464
$P12 Comp-BYG670-A <NA>    206.21435  5.070029e+01    256.91464
$P13 Comp-BYG790-A <NA>    206.21435  5.070029e+01    256.91464
$P14          Time <NA>     74.33615  9.321601e-04     74.33708
```

**Comment by gfinak** [comment]
Data are stored transformed. When plotting, axes are scales to show raw values. The latest patch on RGlab/ggcyto lets you pass axis_inverse_trans=FALSE to autoplot to show raw values (otherwise you need to build up the plot with ggcyto and pass it in there).

**Comment by mikejiang** [comment]
For `plotGate`, you can set `raw.scale = FALSE` to display transformed values, but it is deprecated API and `ggcyto` is recommended visualization tool as @gfinak mentioned, See RGLab/ggcyto#28
