### ISSUE TITLE
Add GatingSet examples the the GitHub readme

### ISSUE THREAD

**Issue by gfinak** [RGLab/ggcyto#30]
Specifically show how to plot transformed and untransformed axis values, how to deal with gates, etc

**Comment by mikejiang** [comment]
We have very detailed vignettes listed here https://bioconductor.org/packages/release/bioc/html/ggcyto.html
Maybe replace readme with update-to-date version of this doc [Feature summary of ggcyto](https://bioconductor.org/packages/release/bioc/vignettes/ggcyto/inst/doc/Top_features_of_ggcyto.html)?

**Comment by gfinak** [comment]
Yes, that's a good idea.

**Comment by mikejiang** [comment]
See the updated README(modified and abridged based on other vignettes) and let me know if what else could be added there.
