### ISSUE TITLE
geom_stats() docs don't match behavior

### ISSUE THREAD

**Issue by gfinak** [RGLab/ggcyto#31]
The `geom_stats` documentation states that the `type` argument can be one of "count", "percent", or "MFI", but when passing "MFI", I get an error.
Additionally,  geom_stats doesn't label some populations properly.
Example:

```
dataDir <- system.file("extdata",package="flowWorkspaceData")
gs <- load_gs(list.files(dataDir, pattern = "gs_bcell_auto",full = TRUE))
```

```
ggcyto(gs[1], aes(x="IgD",y="CD27"),subset= c("CD19andCD20")) + geom_hex(bins=128) +
  geom_gate(c("IgD+CD27+","IgD+CD27-","IgD-CD27+","IgD-CD27-")) + geom_stats(type = "count")
```
![image](https://user-images.githubusercontent.com/1385593/38263888-2f2ecfae-3726-11e8-98f6-bb70c9235c11.png)

 Above the IgD negative populations are not labeled with their statistics.

Also 
```
ggcyto(gs[1], aes(x="IgD",y="CD27"),subset= c("CD19andCD20")) + geom_hex(bins=128) +
  geom_gate(c("IgD+CD27+","IgD+CD27-","IgD-CD27+","IgD-CD27-")) + geom_stats(type = "MFI") +
  theme_cowplot(font_size=18) 

Error in match.arg(type, c("percent", "count")) : 
  'arg' should be one of “percent”, “count”
```
 While `?geom_stats` says
```
type | can be "percent", "count" or "MFI".
```

**Comment by mikejiang** [comment]
I've fixed the stats positioning issue. Now it should always appear at the center of gate boundary or the plot limits (which ever is smaller)
```r
p <- ggcyto(gs[1], aes(x="IgD",y="CD27"),subset= c("CD19andCD20")) + geom_hex(bins=128) + geom_gate() 
p <- p + geom_stats()
p #default is data range
```
![image](https://user-images.githubusercontent.com/1385649/38387949-883a08d0-38ce-11e8-84b0-f19d78dfd480.png)
```r
p + ggcyto_par_set(limits = "instrument")
```
![image](https://user-images.githubusercontent.com/1385649/38387972-a6c112e4-38ce-11e8-8849-fb2685f08dbc.png)
Zoom-in view with manually supplied limits
```r
p + xlim(c(1500, 2200)) + ylim(c(1500, 2500))
```
![image](https://user-images.githubusercontent.com/1385649/38388038-d95e05d6-38ce-11e8-9f8c-9437f6350066.png)
