### ISSUE TITLE
provide subsampling for big FCS data

### ISSUE THREAD

**Issue by mikejiang** [RGLab/ggcyto#32]
It is extremely wasteful of time waiting for the plot to be finished when the number of cells becomes huge. (happened recently when dealing with diva parsing where one FCS has ~9M events).
It won't be necessary to plot all of them and `ggcyto` can have an optional argument to switch on the `random subsampleing` on the data.
e.g.
```r
ggcyto(gs, aes(x,y), sample.ratio = 0.01, sample.threshold = 1e5)
```
So whenever cells exceeds `1e5` and sampling process is triggered. I will turn it off by default (by setting `sample.threshold = Inf`  and let user to turn it on when needed.

**Comment by gfinak** [comment]
@mikejiang actually, I think it should be on by default. Better default user experience in the end.

**Comment by mikejiang** [comment]
Yeah I thought about that just a little concerned that the default subsampling might give user the artifact they don't expect if they are not fully aware of this Behavior. But sure we can turn it on by default

**Comment by mikejiang** [comment]
Testing shows the subsampling greatly improves the plotting speed and produces the comparable 2d bined plots (can't actually tell the difference without looking at the counts at legend)
```r
Unit: seconds
                                             expr       min        lq      mean
                         print(autoplot(gs, "L"))  4.769539  4.769539  4.769539
 print(autoplot(gs, "L", max_nrow_to_plot = Inf)) 29.200597 29.200597 29.200597
```
![image](https://user-images.githubusercontent.com/1385649/39719443-1083b5a0-51ee-11e8-890c-33d3b66cae0c.png)![image](https://user-images.githubusercontent.com/1385649/39719471-1e8c2fba-51ee-11e8-91f8-a9b85957b837.png)

Right now, I am using out-of-box `flowCore::sampleFilter` directly applied to the underlying `fs` without individually checking whether or not  each `flowFrame` needs to be random sampled ( `sampleFilter` automatically decides  it based on the data size and `max_nrow_to_plot`).

We will wait and see if this default behavior causes some confusions so that it becomes necessary for users to be aware of it,  then we can customize this process to throw the message when sampling happens as @gfinak suggested

**Comment by jacobpwagner** [comment]
In https://github.com/RGLab/ggcyto/commit/1fd4be72626eb3b2afbf42abf7e4e3703f03d726 I opted to make it a little easier to add the legend back in.
