### ISSUE TITLE
quadGate with ggcyto

### ISSUE THREAD

**Issue by jchellmuth** [RGLab/ggcyto#33]
Is there any way to use quadGates (flowCore) with ggcyto?
`g.quad <- quadGate(filterId="RG.QuadGate", "GFP"=500, "RFP"=500)
ggcyto(gs[[4]],aes(x=GFP,y=RFP),subset="Live")+geom_hex(bins = 200)+geom_gate(g.quad)`
`Error: ggcyto doesn't know how to deal with gate of class quadGate`

**Comment by gfinak** [comment]
Seems not but there should be. I think a workaround for the time being would be to convert the quadGate to a set of rectangleGates.

**Comment by jchellmuth** [comment]
yes, the rectangleGates are a workaround. However, when plotting two rectangle gates together, you'll only have the stats for the overlapping population visualized:
`
g.gfp <- rectangleGate(filterId="GFP pos","GFP"=c(1000, Inf))
g.rfp <- rectangleGate(filterId="RFP pos","RFP"=c(1000, Inf))

add(gs,g.gfp,parent="Live") 
add(gs,g.rfp,parent="Live") 
recompute(gs)

ggcyto(gs[[4]],aes(x=GFP,y=RFP657),subset="Live")+geom_hex(bins = 200)+geom_gate("GFP pos")+geom_gate("RFP pos")+geom_stats(adjust = 0.1)+ggcyto_par_set(limits = "instrument")+scale_x_flowJo_biexp()+scale_y_flowJo_biexp()
ggsave("plotg_GFP.RFP657_quad.pdf",width = 5,height = 5)`
[plotg_GFP.RFP657_quad.pdf](https://github.com/RGLab/ggcyto/files/2006370/plotg_GFP.RFP657_quad.pdf)

**Comment by mikejiang** [comment]
`quadGate` is an odd ball. It doesn't play well with the openCyto framework where each gate is associate one population and stats (and gate indicies). Even flowJo and Cytobank annotate `quadGate` in a special way and we split it into four rectangle gate when import them. 

What I can do is to add `geom_gate.quadGate` S3 method to do this splitting/coercion automatically. Let me get back to you on this.

**Comment by gfinak** [comment]
This is a good solution @mikejiang .

**Comment by mikejiang** [comment]
pull the latest version 
```r
devtools::install_github("RGLab/ggcyto", ref = "trunk")
```
```r
library(ggcyto)
dataDir <- system.file("extdata",package="flowWorkspaceData")
gs <- load_gs(list.files(dataDir, pattern = "gs_manual",full = TRUE))
fs <- getData(gs, "CD3+")
autoplot(fs, "CD4", "CD8") + ggcyto_par_set(limits = "instrument") + geom_gate(quadGate(`<B710-A>` = 2e3, `<R780-A>` = 2e3)) + geom_stats()
```
![image](https://user-images.githubusercontent.com/1385649/40080017-90c9265e-583e-11e8-934a-02f9bfed00d3.png)

**Comment by jchellmuth** [comment]
Thank you very much for implementing this!
The quad.gate doesn't seem to work with gating.sets but I guess that quad.gates might not fit well into the gating.set framework.
Just one quick question: the geom_stats labels keep overlapping each other no matter which value I use for adjust. Any thoughts on that ?

`g.quad <- quadGate(filterId="GFP.RFP657.qgate", "GFP"=1000, "RFP657"=500)
add(gs,g.quad,parent="Live") 
recompute(gs)
ggcyto(fs[[4]],aes(x=GFP,y=RFP657))+geom_hex(bins = 200)+
  geom_gate(g.quad)+geom_stats()+
  ggcyto_par_set(limits = "instrument")+scale_x_flowJo_biexp()+scale_y_flowJo_biexp()
`
[plot_GFP.RFP657_quadgate.pdf](https://github.com/RGLab/ggcyto/files/2006809/plot_GFP.RFP657_quadgate.pdf)

**Comment by mikejiang** [comment]
The stats label should always positioned at center of the gate boundary (see https://github.com/RGLab/ggcyto/issues/31#issuecomment-379054081).
If you can send me the `fs[[4]]` object as rds file, I can take a look at it.

**Comment by mikejiang** [comment]
Also, I am not sure what you meant by 
>The quad.gate doesn't seem to work with gating.sets

Because `quadGate` is supported by `GatingSet` in the same way as `ggcyto`, i.e. converted and stored as `rectangleGate` automatically for you. See below
```r
library(ggcyto)
dataDir <- system.file("extdata",package="flowWorkspaceData")
gs <- load_gs(list.files(dataDir, pattern = "gs_manual",full = TRUE))
Rm("CD3+", gs)
plot(gs)
```
![image](https://user-images.githubusercontent.com/1385649/40086097-c7abc66e-5851-11e8-93bd-2b24efd5e91b.png)
```r
g <- quadGate(`<B710-A>` = 2e3, `<R780-A>` = 2e3)
add(gs, g, parent = "singlets")
recompute(gs)
plot(gs)
autoplot(gs, getChildren(gs[[1]], "singlets"))
```
![image](https://user-images.githubusercontent.com/1385649/40086135-f5220c7a-5851-11e8-8482-c803a27f4360.png)
![image](https://user-images.githubusercontent.com/1385649/40086149-ff992cec-5851-11e8-8c3b-0db2da020517.png)

**Comment by jchellmuth** [comment]
Ah, I see now where I was making a mistake:
```
# this won't work with gatingSet
ggcyto(gs,aes(x=GFP,y=RFP657),subset="Live")+geom_gate(g.quad)

# but will work with flowSet:
fs <- getData(gs,"Live")
ggcyto(fs,aes(x=GFP,y=RFP657),subset="Live")+geom_gate(g.quad)

# to plot gatingSet with quadGate, use Children:
ggcyto(gs,aes(x=GFP,y=RFP657),subset="Live")+geom_gate(getChildren(gs[[4]],"Live"))
```

Using getCildren, plotting the gatingSet works perfectly. Thanks and sorry for the confusion.

**Comment by mikejiang** [comment]
Neither will work without adding `geom_hex`
```r
# this won't work with gatingSet
ggcyto(gs,aes(x=GFP,y=RFP657),subset="Live")+geom_gate(g.quad)

# but will work with flowSet:
fs <- getData(gs,"Live")
ggcyto(fs,aes(x=GFP,y=RFP657),subset="Live")+geom_gate(g.quad)
```
However, both should work (including `GatingSet` version) when `geom_hex()` added, i.e.
```r
ggcyto(gs,aes(x=GFP,y=RFP657),subset="Live") + geom_hex() + geom_gate(g.quad)

```

**Comment by jchellmuth** [comment]
Here is some of my example data:
https://ln.sync.com/dl/5b500c480/tsn5dxid-57szpumg-9cev8p6q-w65z347x

As mentioned, I can't seem to get the labels not to overlap:
```
load("example.data.Rda")
gs <- GatingSet(fs)
g.singlet <- gate_singlet(fs[[1]], area = "FSC.A", height = "FSC.H",wider_gate = F,filterId = "Singlets")
add(gs,g.singlet) 
recompute(gs)
g.live <- polygonGate(filterId = "Live","FSC.A"=c(6e4,30e4,30e4,6e4),"SSC.A"=c(10e3,10e3,150e3,40e3))
add(gs,g.live)
recompute(gs)
g.quad <- quadGate(filterId="GFP.RFP657.qgate", "GFP"=1000, "RFP657"=500)
add(gs,g.quad,parent="Live") 
recompute(gs)

p <- ggcyto(gs,aes(x=GFP,y=RFP657),subset="Live")+geom_hex(bins = 200)+geom_gate(getChildren(gs[[1]],"Live"))+
  ggcyto_par_set(limits = "instrument")+scale_x_flowJo_biexp()+scale_y_flowJo_biexp()

p+geom_stats(adjust = 0)
p+geom_stats(adjust = 0.5)
p+geom_stats(adjust = 1)
```
![adjust0](https://user-images.githubusercontent.com/27713165/40089167-4b014efa-5878-11e8-8700-55eaa8f8b1fc.jpg)
![adjust1](https://user-images.githubusercontent.com/27713165/40089172-524e72fa-5878-11e8-8708-88e921e8a448.jpg)
![adjust05](https://user-images.githubusercontent.com/27713165/40089174-549c0a2c-5878-11e8-964b-8c1792d08f0b.jpg)

**Comment by jchellmuth** [comment]
as for adding the gate - sorry, I did indeed forget to add geom_hex. 
However, I do believe you have to use getChildren to plot because the following does not work:
```
ggcyto(gs,aes(x=GFP,y=RFP657),subset="Live")+geom_hex(bins = 200)+geom_gate(g.quad)+
  geom_stats()+
  ggcyto_par_set(limits = "instrument")+scale_x_flowJo_biexp()+scale_y_flowJo_biexp()
Error in add_ggcyto_gs(e1, e2) : 
  geom_gate must be added before adding geom_stats!
```
whereas this works fine:
```
ggcyto(gs,aes(x=GFP,y=RFP657),subset="Live")+geom_hex(bins = 200)+geom_gate(getChildren(gs[[1]],"Live"))+
  geom_stats()+
  ggcyto_par_set(limits = "instrument")+scale_x_flowJo_biexp()+scale_y_flowJo_biexp()
```
![quadgate children](https://user-images.githubusercontent.com/27713165/40089352-4baf8604-5879-11e8-947e-6f8d1ec9f491.jpg)

**Comment by mikejiang** [comment]
For the `stats label` positioning, I found where the issue was. The current `compute_stats` function looks at both data and gate range for computing stats location. And it assumes the data and gate are already transformed. (it's been the common workflow that data is transformed before any gating takes place.)
Apparently your workflow breaks this assumption, which defines the gates at raw linear scale and does in-line logicle transformation during the plotting. 
I will see what I can do to fix this.

**Comment by jchellmuth** [comment]
Thank so much for looking into this!
Yes, indeed, I usually don't transform the data but use the (very convenient) ggcyto scales (i.e. scale_x_flowJo_biexp) to visualize appropriately. I find this approach much more convenient for a number of reasons, especially being able to quickly switch scales when plotting.

**Comment by mikejiang** [comment]
Understood. @gfinak and I were having some conversation on the related topic where potentially `openCyto` keeps the data at raw scale and do all the transformation on the fly at gate level, which is similar to the workflow of flowJo and diva. But it requires the big changes in our framework.

**Comment by mikejiang** [comment]
I've fixed the `stats` position issue for `in-line` transformation. See below
```r
ggcyto(fs,aes(x=GFP,y=RFP657))+geom_hex()+geom_gate(g.quad)+
  ggcyto_par_set(limits = "instrument")+scale_x_flowJo_biexp()+scale_y_flowJo_biexp()+geom_stats()
```
![image](https://user-images.githubusercontent.com/1385649/40148050-f021c3c6-5920-11e8-896f-f526113c1410.png)

**Comment by jchellmuth** [comment]
works great - thanks!
and, in general, many thanks for this great package. ggcyto has really made facs data anlysis in R fun, efficient and easy!

**Comment by mikejiang** [comment]
Good to hear!
