### ISSUE TITLE
geom_gate(aes(col = "node")) - map geom_gate col to nodes

### ISSUE THREAD

**Issue by DillonHammill** [RGLab/ggcyto#35]
Hi Mike,

Just wondering whether we can map the colour of the gate to the name of the population (i.e. differnet gate colour for each population)? It would be nice to show the node names for a given gate in the legend...

Not sure if this is possible?

Thanks.
Dillon

**Comment by mikejiang** [comment]
good point. Will need come up an intuitive yet simple argument to control what to display
 instead of `type = "gate_name"`, we can do
```r
geom_stats(type = "count", show_gate_name = TRUE)
```
but this won't meet the need of only showing the `gate name`

**Comment by gfinak** [comment]
can we pass a vector `type=c("count","gate_name")`

**Comment by mikejiang** [comment]
Then we will use space to separate two strings. I like that!

**Comment by DillonHammill** [comment]
I have accomplished this using the plotrix package for base graphics. It would be great if we could do it with ggcyto - overcrowding may be an issue...

**Comment by mikejiang** [comment]
I am not sure what your use case will be (why not post whatever example plot you were talking about).
`ggcyto` was designed in the way that you typically don't expect too many gates placed on 2d space for any given parent population,

**Comment by DillonHammill** [comment]
I guess the most gates would be the quadrant gate situation....in some situations the channel/markernames are not sufficient to describe the population just by looking at the plot - it would be nice to have this information somewhere in plot so you don't have to refer to the text to figure out what the populations are...

**Comment by mikejiang** [comment]
This is not a good `quadGate` in the first place

**Comment by gfinak** [comment]
@DillonHammill I see what you're getting at.  Would some transparency for the background of the label be acceptable in the meantime?

**Comment by gfinak** [comment]
@mikejiang  I wonder if we could leverage the [ggrepel](https://cran.r-project.org/web/packages/ggrepel/vignettes/ggrepel.html) package to label the populations in the gates. The idea would be to have the gate name as the label, but rather than place it in the center of the gate, place it somewhere else (using ggrepel) and have it point to the center of the gate.

**Comment by DillonHammill** [comment]
Yeah that would help!

**Comment by gfinak** [comment]
@DillonHammill can you try passing `aes(alpha=0.5)` to the `geom_stats()` layer?

**Comment by gfinak** [comment]
@DillonHammill just a note that passing alpha to geom_stats works for me when using `ggcyto` but not `autoplot`.

**Comment by DillonHammill** [comment]
Great! Thanks guys!

**Comment by mikejiang** [comment]
@gfinak , see this
```r
p + geom_stats(type = c("gate_name", "percent"), fontface= "bold")
```
![image](https://user-images.githubusercontent.com/1385649/41943263-9e46bcc6-7957-11e8-8af7-be2702004bc3.png)

**Comment by mikejiang** [comment]
I will look into ggrepel  when I get a chance

**Comment by DillonHammill** [comment]
That is excellent thanks @mikejiang!
