### ISSUE TITLE
object 'ggplot.data.frame' not found

### ISSUE THREAD

**Issue by efinlay** [RGLab/ggcyto#37]
I don't know if this is an issue with ggcyto or R versions or updates.
ggcyto was working perfectly, then I updated R and now I get the same error for each attempt to plot.

> version
               _                           
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          5.0                         
year           2018                        
month          04                          
day            23                          
svn rev        74626                       
language       R                           
version.string R version 3.5.0 (2018-04-23)
nickname       Joy in Playing              

> library(ggcyto)
> library(flowCore)
#load sample flowset
> fs <- read.flowSet(path=system.file("extdata", "compdata", "data",
+ package="flowCore"), name.keyword="SAMPLE ID",
+ phenoData=list(name="SAMPLE ID", Filename="$FIL"))
> autoplot(fs,"FSC-H")

Error in get(name, envir = asNamespace(pkg), inherits = FALSE) : 
  object 'ggplot.data.frame' not found

Googling hasn't produced anything comprehensible about what this might mean - is there a way to fix it?
Thank you

**Comment by efinlay** [comment]
For additional information
ggplot(fs, aes("FSC-H"))+geom_density()
produces an appropriate looking curve

> ggcyto(fs, aes(FSC-H))+geom_density()
Error in get(name, envir = asNamespace(pkg), inherits = FALSE) : 
  object 'ggplot.data.frame' not found

and ggplot(fs, aes("FSC-H", "SSC-H"))+geom_hex() produces a solid blue screen

**Comment by DamienSTI** [comment]
I get the exact same issue as of today.

> autoplot(gs_comp_trans[[6]])
Error in get(name, envir = asNamespace(pkg), inherits = FALSE) : 
  object 'ggplot.data.frame' not found

NB: autoplot was working perfectly fine until yesterday.

> version
               _                           
platform       x86_64-apple-darwin15.6.0   
arch           x86_64                      
os             darwin15.6.0                
system         x86_64, darwin15.6.0        
status                                     
major          3                           
minor          5.0                         
year           2018                        
month          04                          
day            23                          
svn rev        74626                       
language       R                           
version.string R version 3.5.0 (2018-04-23)
nickname       Joy in Playing     

Thank you in advance for your help,
Damien

**Comment by gfinak** [comment]
Last commit was 9 days ago. So this is likely because you updated ggplot2?

**Comment by DamienSTI** [comment]
Thank you Greg.
First re-installed ggplot2 v2.2.1 which failed again but v2.2.0 works fine so far. :-)
I would like to take profit to also thank you for developing these great tools.
Damien

**Comment by mikejiang** [comment]
As @gfinak said, it was due to the api changes from the latest ggplot2. I've just pushed the fix and please pull the latest ggcyto from trunk branch and that should work with the latest ggplot2 3.0

**Comment by RosaKCL** [comment]
Hi,
Sorry to bother you again but I am quite new in R and I am also experiencing this issue. Could you be more precise as to how to pull the latest ggcyto from trunk branch to fix this issue or redirect me to the relevant literature?
Thanks a lot for your help!
Rosa.

**Comment by efinlay** [comment]
I was able to do it using DevTools, the important part is the ref=trunk to make sure that's what you get

#install.packages("devtools")
#devtools::install_github("RGLab/ggcyto", ref='trunk')

**Comment by DamienSTI** [comment]
@efinlay, now works for me, thanks!

**Comment by FloraVincent** [comment]
This thread just saved me 2 more hours of googling ! 
I was also running under the issue of 
"Error in get(name, envir = asNamespace(pkg), inherits = FALSE) :
object 'ggplot.data.frame' not found" even though it had already worked great in the past.
@efinlay your solution fixed it so THANKS !

**Comment by malcook** [comment]
is this slated for "release" to BioC soon?  Or, already done?  Inquiring minds (acb@stowers.org) are seeking release stability....

**Comment by mikejiang** [comment]
It's in bioc release already.
