### ISSUE TITLE
Newbie: Can't reproduce FacsDiva Output

### ISSUE THREAD

**Issue by r-cheologist** [RGLab/ggcyto#46]
I started to work with ggcyto to remedie the limitations of FacsDiva output. The goal is to reproduce the following plot:
![AMS109_1-12_4_25042019104856](https://user-images.githubusercontent.com/3259333/58664245-499e6e80-82fc-11e9-9c8e-988a166aba2c.png)
The code I came up with based on the github trunk versions of ggcyto and its cytoverse dependencies, as well as a imported version of the FacsDiva `XML` ([see here](https://github.com/RGLab/CytoML/issues/57#issue-449637433)) like this:

    ggcyto::ggcyto(
        gs %>% subset(name == "AMS109 1-12_4_007.fcs"),
        ggplot2::aes_q(
          x = "FSC-H",
          y = "FITC-A"),
        subset = "root") +
      ggplot2::geom_point() +
      ggcyto::geom_gate("/P1")

The resulting plot, however,appears to derive from a different or differently scaled dataset!? :
![Rplot](https://user-images.githubusercontent.com/3259333/58664673-232d0300-82fd-11e9-96a2-acd8d97828de.png)
Could anyone help me to combat my folly?

**Comment by mikejiang** [comment]
For visualizing the gate,  `autoplot(gs, "/P1")` should do.

**Comment by mikejiang** [comment]
for the customized dot plot, try ``ggcyto(gs, `FITC-A` ~ `FSC-H`) + geom_point() + geom_gate("/P1")``

**Comment by r-cheologist** [comment]
I believe I had erroneously associated pre-export *.fcs files with the export *.xml, thus the discrepancy.
In a new data set I meanwhile got it to work.
