### ISSUE TITLE
set the default limits to the actual data range

### ISSUE THREAD

**Issue by mikejiang** [RGLab/ggcyto#47]
There have been numerous incidents (e.g. #15, RGLab/flowCore#155) related to issues of the incorrect/inaccurate `instrument range` (i.e. from `$PnR` keyword) prevents the data from being displayed properly.  
The cause is rather obscure and thus confusing to the users. Thus we will consider to switch to the `data range` as the default `limits` setting. As for the concern of outlier data points (which was the main reason for using `instrument range` as default), the problem will be more obvious for the user to observe and thus easily come to the solution on their own by simply adjusting the limits by `ggcyto_part_set(limits=..)` or `coord_cartesian`

**Comment by SamGG** [comment]
That's a good question. If you are considering ignoring the instrument range, what about the  truncate_max_range parameter (being TRUE by default) of the read.FCS function?

**Comment by mikejiang** [comment]
So far we've only seen the cases where `intrument range` is exaggerated (i.e. far bigger than the actual data scale), so `truncate_max_range` won't affect the data value that's been read from FCS.
Also we are not ignoring it, just set the preference between the two ranges when it comes to display the data in plots.

**Comment by SamGG** [comment]
Thanks for your feedback.
FYI, in the output of cytofkit, the range of the clustering channels are set to the maximum-minimum, e.g. 19-1 = 18, which leads to truncation and the merging of the last two clusters. This will be corrected, but I think such cases could occur because of the definition of the PxR.

**Comment by mikejiang** [comment]
completed
