### ISSUE TITLE
Howto color points by gate memership?

### ISSUE THREAD

**Issue by r-cheologist** [RGLab/ggcyto#48]
I have managed to load data and present it equivalently to what my FACS Diva template gives me, both using `geom_he` and `geom_points` (it's not that many events, so `points` remains handle-able), as well as showing the gates.

I would like to now color all points that fall within one gate - how to do that?

**Comment by mikejiang** [comment]
see `?geom_overlay`

**Comment by r-cheologist** [comment]
Thank you for the pointer - exploration of this is made difficult, as the examples in the github trunk branch are broken:

    > library(ggcyto)
    > dataDir <- system.file("extdata",package="flowWorkspaceData")
    > gs <- load_gs(list.files(dataDir, pattern = "gs_manual",full = TRUE))
    Error in if (!file.exists(path)) stop(path, "' not found!") : 
    argument is of length zero

**Comment by mikejiang** [comment]
You need to install `flowWorkspaceData` bioconductor package
