### ISSUE TITLE
Bug? Unexpected faceting in `geom_overlay` 

### ISSUE THREAD

**Issue by r-cheologist** [RGLab/ggcyto#49]
Have a look at this:

    library(ggcyto)
    dataDir <- system.file("extdata",package="flowWorkspaceData")
    gs <- load_gs(list.files(dataDir, pattern = "gs_manual",full = TRUE))
    p <- autoplot(gs, "CD3+")

    p +
      geom_overlay(data = "DPT" , size = 0.3, alpha = 0.7, color = "red") +
      geom_overlay(data = "DNT", size = 0.3, alpha = 0.7, color = "blue")

**Comment by r-cheologist** [comment]
Ok. This is apparently dpendent on the data set ... can't reproduce. Closing.

**Comment by mikejiang** [comment]
You need to install `flowWorkspaceData` bioconductor package
