### ISSUE TITLE
no such file or directory: '"/usr/local/lib/R/3.6/site-library/Rhdf5lib/lib/libhdf5.a"'

### ISSUE THREAD

**Issue by GeroKn** [RGLab/ggcyto#52]
Hi all,

I hope this is the right platform to post this question: When I try to install ggcyto, I get two clang errors: libhdf5.a and libsz.a are not found. But these files are exactly where it is looking for them (path see above).
I was wondering why there are two sets of quotes around that path?

`clang++ -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/usr/local/opt/gettext/lib -L/usr/local/opt/readline/lib -L/usr/local/lib -L/usr/local/Cellar/r/3.6.1_1/lib/R/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/readline/lib -L/usr/local/lib -o ncdfFlow.so RcppExports.o bitOps.o hdfFlow.o init.o readFrame.o "/usr/local/lib/R/3.6/site-library/Rhdf5lib/lib/libhdf5.a" "/usr/local/lib/R/3.6/site-library/Rhdf5lib/lib/libsz.a" -lz -L/usr/local/Cellar/r/3.6.1_1/lib/R/lib -lR -lintl -Wl,-framework -Wl,CoreFoundation
clang: error: no such file or directory: '"/usr/local/lib/R/3.6/site-library/Rhdf5lib/lib/libhdf5.a"'
clang: error: no such file or directory: '"/usr/local/lib/R/3.6/site-library/Rhdf5lib/lib/libsz.a"'`

Thanks a lot in advance!
Best,
Gero

**Comment by SamGG** [comment]
Hi,
I think Jake, Mike or Greg will reply soon.
Already issued at https://github.com/RGLab/ncdfFlow/issues/49 which sounds a better place for ncdfFlow questions.
Best.

**Comment by GeroKn** [comment]
Thank you!

**Comment by jacobpwagner** [comment]
@GeroKn , are you installing `Rhdf5lib` from GitHub `master` branch or Bioconductor? It looks like the double quotation on that path may be related to https://github.com/grimbough/Rhdf5lib/commit/dbec92f4c839501a30ef8eca80212375c24884b3 / https://github.com/grimbough/Rhdf5lib/commit/dfb8f44941c98f95299642e35f64342123d41b4b. Still looking in to it, as this still doesn't explain https://github.com/RGLab/ncdfFlow/issues/49

**Comment by GeroKn** [comment]
Hi,

I installed it from Bioconductor.

Best! And thanks for looking into it!

On 14. Oct 2019, at 18:49, Jake Wagner <notifications@github.com<mailto:notifications@github.com>> wrote:


@GeroKn<https://github.com/GeroKn> , are you installing Rhdf5lib from GitHub master branch or Bioconductor? It looks like the double quotation on that path may be related to grimbough/Rhdf5lib@dbec92f<https://github.com/grimbough/Rhdf5lib/commit/dbec92f4c839501a30ef8eca80212375c24884b3> / grimbough/Rhdf5lib@dfb8f44<https://github.com/grimbough/Rhdf5lib/commit/dfb8f44941c98f95299642e35f64342123d41b4b>. Still looking in to it, as this still doesn't explain RGLab/ncdfFlow#49<https://github.com/RGLab/ncdfFlow/issues/49>

**Comment by jacobpwagner** [comment]
@GeroKn , will you pull https://github.com/RGLab/ncdfFlow/commit/26912e172befbc79818d95f524f1dbda86ce8420 and rebuild `ncdfFlow` (or just `devtools::install_github("RGLab/ncdfFlow", ref="trunk")` ) and see if that fixes the issue?

**Comment by jacobpwagner** [comment]
Alright, I think this is resolved (see further discussion on https://github.com/RGLab/ncdfFlow/issues/49). So I'm going to go ahead and close it. @GeroKn, let me know if there are any more issues.
