### ISSUE TITLE
max_nrow_to_plot not working on flowFrames

### ISSUE THREAD

**Issue by gunthergl** [RGLab/ggcyto#53]
When plotting a single FlowFrame, thus calling ggcyto.default, max_nrow_to_plot is not working. 

	library(ggcyto)
	data(GvHD)
	fs <- GvHD[1]
	ggcyto(fs, aes(x = `FSC-H`, y =  `SSC-H`)) + geom_hex(bins = 128)
	ggcyto(fs, aes(x = `FSC-H`, y =  `SSC-H`), max_nrow_to_plot=500) + geom_hex(bins = 128)

	ggcyto(fs[[1]], aes(x = `FSC-H`, y =  `SSC-H`)) + geom_hex(bins = 128)
	ggcyto(fs[[1]], aes(x = `FSC-H`, y =  `SSC-H`), max_nrow_to_plot=500) + geom_hex(bins = 128)

![removeme1](https://user-images.githubusercontent.com/14908309/67076400-5e857c80-f18d-11e9-93c6-4e04967a953d.png)
![removeme2](https://user-images.githubusercontent.com/14908309/67076234-0a7a9800-f18d-11e9-9136-6d8417492279.png)
![removeme3](https://user-images.githubusercontent.com/14908309/67076259-17978700-f18d-11e9-82e8-25c3e28ed26e.png)
![removeme4](https://user-images.githubusercontent.com/14908309/67076264-1a927780-f18d-11e9-8037-2849094267de.png)

**Comment by jacobpwagner** [comment]
Right you are. It should be good after e2ee428. Using your same code snippet:
![plot_zoom_png](https://user-images.githubusercontent.com/43548373/67131990-d7033200-f1bb-11e9-98b0-a7b8d87cc227.png)
![plot_zoom_png](https://user-images.githubusercontent.com/43548373/67131994-dbc7e600-f1bb-11e9-9f3e-64d1affa14d1.png)
![plot_zoom_png](https://user-images.githubusercontent.com/43548373/67131997-df5b6d00-f1bb-11e9-9380-09e4e7eff50d.png)
![plot_zoom_png](https://user-images.githubusercontent.com/43548373/67132000-e3878a80-f1bb-11e9-99d0-65bcb86c4938.png)
