### ISSUE TITLE
Unexpected faceting in geom_overlay() - Overlaying 1D plots

### ISSUE THREAD

**Issue by northNomad** [RGLab/ggcyto#60]
I have a gatingSet with 25 experiments and I want to overlay density-plot of a particular channel in two of the gating hierarchies within my gatingSet (the 12th and 24th experiments, specifically). 

I plotted a 1D density plot of a gating hierarchy (subsetted from a gatingset).
I then created a ncdfFlowSet with the function 'gs_pop_get_data', of which I want to overlay on top of my 1D plot. 

```
p <- ggcyto(gs[[12]], aes(x=`FL4-H`), subset = "Lymphocytes") + geom_density()
f <- gs_pop_get_data(gs[[24]], "Lymphocytes")

p + geom_overlay(f)
```

Instead of getting an overlaid density plot, I get the following - an unexpected faceting.

![Rplot](https://user-images.githubusercontent.com/60832021/74094787-cfda9980-4ab4-11ea-8cc0-3d4f3f1bed90.jpeg)

I saw that someone encountered a similar problem in the 'closed issue' section and MikeJiang suggested him to install the Bioconductor package "flowWorkspaceData". 
I did but I'm still running into the same issue. 

Please let me know what I can do / what additional information I need to supply to resolve this issue!

Many thanks in advance!

**Comment by gfinak** [comment]
Ggcyto will always facet by sample. Try adding `+ facet_null()` or use `ggplot` directly.

**Comment by northNomad** [comment]
> Ggcyto will always facet by sample. Try adding `+ facet_null()` or use `ggplot` directly.

This worked!
Thank you so much!
