### ISSUE TITLE
ggcyto cannot run on gatingset class object with version (3.3) of ggplot2 on R 3.6.3

### ISSUE THREAD

**Issue by FMKerckhof** [RGLab/ggcyto#63]
Dear, 

Currently I am running into issues with the Bioconductor version of ggcyto, with ggplot2 v. 3.3.0.

```r
library(flowAI) # to get a flowset
library(ggcyto)
### load & inspect dataset -----------------------------------------------------
data("Bcells") # from flowAI
attributes(Bcells)
colnames(Bcells)
### preformat dataset ----------------------------------------------------------
Bcells_transformed <- flowCore::transform(Bcells,`SSC-H`=asinh(`SSC-H`),
                                          `FSC-H`=asinh(`FSC-H`))
### create gatingset ------------------------------------------------------------
bcellmat <- matrix(c(11.5,12.2,13,13,10,13,14,11),ncol=2, nrow=4)
colnames(bcellmat) <- c("FSC-H","SSC-H")
polyGateBcell <- polygonGate(.gate=bcellmat, filterId = "B Cells")

gs_bcells <- GatingSet(Bcells_transformed)
gs_bcells_gate1 <- flowWorkspace::add(gs_bcells,polyGateBcell)
recompute(gs_bcells)
### run ggcyto -----------------------------------------------------------------
ggcyto(gs_bcells,aes(x=`FSC-H`,y=`SSC-H`))
```

This gives an error that has been documented before (#39), but apparently is not resolved (anymore?):

```
> ggcyto(gs_bcells,aes(x=`FSC-H`,y=`SSC-H`))
Error in get(name, envir = asNamespace(pkg), inherits = FALSE) : 
  object 'update_theme' not found
```

I have seen that on this Github, there is a specific branch `ggplot3.3` with even a commit that appears to tackle the issue (def48abcb85696e8c64c26d6e79040a30519cb04).

However, when installing from Github from this specific branch I am asked to install Github (development) versions from FlowWorkspace, Cytolib, ... So far no problem, but I am also asked to install a dev version of FlowCore. Since I have other packages depending on that, I am not keen to do so. 

Is there an alternative way to resolve this issue without breaking other dependencies? Any help would be warmly appreciated.

**Comment by FMKerckhof** [comment]
Possibly relevant is that ggcyto is shown as "newly broken" on ggplot2 revdep: https://github.com/tidyverse/ggplot2/blob/master/revdep/problems.md#ggcyto

**Comment by jacobpwagner** [comment]
The `ggplot2` 3.3 compatibility commit you cited (https://github.com/RGLab/ggcyto/commit/def48abcb85696e8c64c26d6e79040a30519cb04) has been merged to the `master` branch here on GitHub as well as to the development branch of Bioconductor. So it shouldn't be "newly broken" much longer.

With regard to updating `flowCore`, you have already installed the GitHub versions of `cytolib` and `FlowWorkspace`, so I would recommend doing the same for `flowCore` for the sake of compatibility. The most recent update to a `ggcyto` direct version dependency was `flowWorkspace`, about 11 months ago (https://github.com/RGLab/ggcyto/commit/d04747bcd13ec8c835d2c20e6a0d0f3c3652a998). So I'm guessing the prompt to update `flowCore` is coming from updating `flowWorkspace`, which itself depends on more recent changes to `flowCore`. So basically, if you want to use the newer `ggcyto` that is compatibile with `ggplot2` v3.3.0, you should update all of the dependent packages.

Is there a particular reason you are holding `flowCore` back? Which dependent packages are you worried about?

**Comment by mikejiang** [comment]
What is your `ggcyto` version? The latest release is `1.14.1`, which should already have fixed this issue.

**Comment by FMKerckhof** [comment]
@mikejiang : Sorry for not letting you know, I was using ggcyto from the current bioconductor stable (bioconductor v. 3.10, ggcyto 1.12.1). 
@jacobpwagner I think I should have rephrased my question: is there any way to use ggcyto with the stable branch of bioconductor and ggplot2 3.3.0?

**Comment by FMKerckhof** [comment]
@mikejiang thank you for your answer, by updating to bioconductor v3.10 and, consequently, ggcyto 1.14.1, things appear to be working fine again. My apologies for missing this in the first place.

**Comment by jacobpwagner** [comment]
@FMKerckhof , ah yeah, sorry. I was kind of misunderstanding the question. Good to hear it worked out.
