### ISSUE TITLE
as.ggplot does not work for ggcyto_GatingLayout objects resulting from autoplot

### ISSUE THREAD

**Issue by jacobpwagner** [RGLab/ggcyto#67]
This is related to #54 in that it involves `ggplot2`-interfacing functions to handle `ggcyto_GatingLayout` objects, but the specifics and solution are a little different. Basically, it would be nice to be able to gracefully convert `autoplot` outputs to standard `ggplot` objects using `as.ggplot`, but this is currently not possible.

Simple reprex:

`autoplot` output isn't handled by `as.ggplot`
```
library(flowCore)
library(flowWorkspace)
library(ggcyto)

gs <- load_gs(system.file("extdata", "gs_manual", package = "flowWorkspaceData"))

# Produces a ggcyto_GatingLayout object which as.ggplot doesn't handle yet
p <- autoplot(gs[[1]], "CD3+")
p
is(p)
as.ggplot(p)
```
The error:
```
> as.ggplot(p)
Error in as.ggplot(p) : object 'name' not found
```
However, standard `ggcyto` objects are handled just fine:
```
p <- ggcyto(gs[[1]], aes("CD3", "SSC-A"), subset = "singlets") +
  geom_hex() +
  geom_gate(gh_pop_get_gate(gs[[1]], "CD3+")) +
  axis_x_inverse_trans()
# This is a simple ggcyto object that can be converted
p
is(p)
as.ggplot(p)
```
This is probably not too difficult to remedy and could be worth it to be able to hook all `ggcyto` outputs in seamlessly to the package ecosystem stemming off of `ggplot2`. The use case highlighting this came from @juyeongkim who was trying to use `plotly::ggplotly` on `autoplot` output and running in to the error above. But, the bottom approach using a standard `ggcyto` call works. e.g:

```
library(plotly)
p <- ggcyto(gs[[1]], aes("CD3", "SSC-A"), subset = "singlets") +
  geom_hex() +
  geom_gate(gh_pop_get_gate(gs[[1]], "CD3+")) +
  axis_x_inverse_trans()
p
ggplotly(as.ggplot(p))
```

**Comment by mikejiang** [comment]
However `ggcyto_GatingLayout` is `arrangeGrob` to a `gtable` object, which isn't `ggplot` object but rather a collection of lower-level `grid` data structures.

**Comment by jacobpwagner** [comment]
Yeah. You're right. Arranging individual `ggplot` objects is something other `ggplot2` extensions are expected to manage themselves, so we should probably should expect users to do the same with individual coerced `ggcyto` objects as well. I was thinking about the single-plot case, but that logic can't be applied to `autoplot` output in general.

**Comment by malcook** [comment]
FWIW: I have just encountered the same error upon my similarly making the erroneous assumption that as.ggplot would work in this case

For your consideration @mikejiang  or @jacobpwagner (and anyone else succumbing to the same error), based on a quick review of the aforementioned reference #54 and https://github.com/RGLab/ggcyto/commit/425d2aec40530bb51926af772786e4f23f3b5edd, I cobbled this function that works(?) to arrange (a possible mix of) both `ggcyto` and `ggcyto_GatingLayout` objects and wonder if you think it is a useful abstraction (or am I rather hiding implementation that users of ggcyto should be comfortable with?):

```
  library(cowplot)
  library(function)
  ggcyto_plot_grid<-function(plotlist,...) {
    ggcyto_coerce <- function(x) {
      ifelse(isa(x, "ggcyto_GatingLayout"),
        functional::Curry(ggcyto::ggcyto_arrange, nrow = 1),
        ifelse(isa(x, "ggcyto"), ggcyto::as.ggplot, identity)
      )(x)
    }
    cowplot::plot_grid(plotlist = lapply(plotlist, ggcyto_coerce), ...)
  }  
```
