### ISSUE TITLE
Question regarding limits

### ISSUE THREAD

**Issue by SofieVG** [RGLab/ggcyto#75]
Hi,

I wanted to set limits (with xlim() and ylim()) on the autoplot to ensure the same scale was used across multiple plots. However, this did not the effect I had hoped for: the original limits were kept, if the limits assigned where higher then the original nothing changed, if they were lower the data values were cut off but the plot itself did not change its axes. Am I using the syntax wrong, or is there an issue with the package? Many thanks for your help!

I tried to make a reproducible example below to showcase what I mean:

![image](https://user-images.githubusercontent.com/1912811/109999491-90f83100-7d12-11eb-85e6-b72f6ef60274.png)

library(flowCore)
library(ggCyto)
file.name <- system.file("extdata","0877408774.B08",
                         package="flowCore")
x <- read.FCS(file.name, transformation=FALSE)
plots <- list(p1 = autoplot(x, "FL1-H", "FL2-H", bins = 128) +
                ggtitle("Original"),
              p2 = autoplot(x, "FL1-H", "FL2-H", bins = 128) +
                xlim(c(0, 2000)) + 
                ylim(c(0, 2000)) +
                ggtitle("2000 - 2000"),
              p3 = autoplot(x, "FL1-H", "FL2-H", bins = 128) +
                xlim(c(0, 500)) + 
                ylim(c(0, 500)) +
                ggtitle("500 - 500"))
ggpubr::ggarrange(plotlist = lapply(plots, print), ncol = 3)

Also not sure why I needed the lapply print to get ggarrange to work, but this is working now so if that can't be solved easily that doesn't matter too much.

All the best,
Sofie

**Comment by jacobpwagner** [comment]
I think you are looking for `ggcyto_par_set`:

```
plots <- list(p1 = autoplot(x, "FL1-H", "FL2-H", bins = 128) +
                ggtitle("Original"),
              p2 = autoplot(x, "FL1-H", "FL2-H", bins = 128) +
                ggcyto_par_set(limits = list(x = c(0, 2000), y= c(0, 2000))) +
                ggtitle("2000 - 2000"),
              p3 = autoplot(x, "FL1-H", "FL2-H", bins = 128) +
                ggcyto_par_set(limits = list(x = c(0, 500), y= c(0, 500))) +
                ggtitle("500 - 500"))
ggpubr::ggarrange(plotlist = lapply(plots, print), ncol = 3)
```
![image](https://user-images.githubusercontent.com/43548373/110032543-1b2d9e80-7ced-11eb-999d-ee073273073a.png)

**Comment by SofieVG** [comment]
Indeed, thanks a lot!
