### ISSUE TITLE
Facet ordering in ggcyto

### ISSUE THREAD

**Issue by Close-your-eyes** [RGLab/ggcyto#76]
Dear all,

I have a gating set, gs, which I have annotated with a number of pData (accessed and changed via pData(gs)). With columns in the pData one can created facetted plots.

In order to change the order of facets in the ggplot universe I usually convert columns of a data.frame to factors and change the order of factor levels. This then affects the facet order in the plots.

Problem here is that the pData only stores characters but not factors, so I cannot easily change the order of facets in the plots created with ggcyto as I usually do with other ggplots.

Is there a solution or an alternative that I am not aware of, to define the order of facets in ggcyto?

Thank you.

**Comment by marcelcosta** [comment]
Hi!

I have run with the same issue than yourself. As you said, pData only stores characters so my only solution for now has been converting it in the same ggcyto:
```R
ggplot+facet_wrap(.~factor(variable, levels=c("ex1","ex2","ex3"))
```
It would be nice to have it functioning as every ggplot... :)

**Comment by Close-your-eyes** [comment]
That's actually a good solution to me.
The only downside is that you have to write that line multiple times for multiple plots.

Thank you!
