### ISSUE TITLE
Plotting overlay of density plot from two subsets in a GatingSet

### ISSUE THREAD

**Issue by john-lee-johnson** [RGLab/ggcyto#9]
Hello, I'm new to R and doing flow analysis in R. I read in my flow set, compensated, transformed, applied a gating template to create a gating set. My question is: How can I take my gating set and do an overlaid density plot of two populations (e.g., "CD4+" and "CD8+") for some parameter (e.g., 582/15 Green-A) using the densityplot function.

The following code produces a plot that is very similar to what I would like, but I figure there must be an easier way if I have already produced a GatingSet object

`library(flowViz)`
`data(GvHD)`
`fs <- GvHD[1:5]`
`fs <- transform(fs, estimateLogicle(fs[[1]], colnames(fs)[-c(1:2)]))`
`g <- rectangleGate(```FL1-H```= c(3, 5))`
`pos <- Subset(fs, g)`
`densityplot(~```FL1```, fs, margin = F, overlay = list(pos = pos), stack = F, filter = g, fitGate = F)`

(sorry I had some trouble getting the backticks into the codeblock)

Using ggcyto I was able to use the GatingSet and subset a population and make a density plot for a certain channel, but I am unsure of how to overlay with a second population subset from the same GatingSet.

`ggcyto(gs.cl13_empty[[1]], aes(x = Tcf1), subset = "CD4+") + geom_density(aes(y=..scaled..))`

Thank you much for the help!

**Comment by gfinak** [comment]
What you're looking for is geom_overlay()

Greg Finak

**Comment by mikejiang** [comment]
First of all,  the recommended workflow should be ` flowSet`->`GatingSet`->`compensated`->`transformed`->`applied a gating template` . This will ensure `compensation` and `transformation` are stored within `GatingSet` which are important for plotting as well as porting and reproducing the entire analysis in other platform(e.g. `cytobank` and `flowJo`, see example workflow in the linked vignette from RGLab/CytoML#5)

secondly, `geom_overlay` currently only works with `2d` plot (i.e. `geom_hex`). If you can provide the convincing reason for choosing `1d overlay` plot, we can certainly consider supporting it in `ggcyto`.  Frankly, I haven't seen single real use case from users ever since I implemented it in `flowViz`

**Comment by john-lee-johnson** [comment]
Is my workflow wrong? I read in FCS to flowSet, compensate it, transform it, create GatingSet on the compensated, transformed flowSet, and then apply gating template.

I can't seem to find `geom_overlay`, it doesn't seem to be available for `ggcyto` version 1.0.5 from bioconductor? I'm interested in 1d overlay plots because it's a popular feature in FlowJo analysis to overlay populations on top of each other in histograms. Actually, coming from a FlowJo world, 1d overlays are much more common than 2d overlays. It's not a super big deal because I can export each population separately and use `ggplot2` to create overlaid density plots, just wondering if there was a more direct way to do it.

Thanks for all the help, sorry for my naivete

**Comment by gfinak** [comment]
No, your workflow seems fine. Maybe install from the BioConductor development branch or our RGLab/ggcyto trunk branch.

**Comment by mikejiang** [comment]
As I said, you will be better off down the road if you change the workflow as this [autogating example](https://github.com/RGLab/CytoML/blob/master/vignettes/HowToExportGatingSet.Rmd)

**Comment by john-lee-johnson** [comment]
Oh okay, I understand now! Thanks!

**Comment by mikejiang** [comment]
@john-lee-johnson ， **overlaid density plot** is now supported by `geom_overlay` . See the **geom_overlay** section of the [vignette](https://github.com/RGLab/ggcyto/blob/trunk/vignettes/ggcyto.GatingSet.md) for examples.

**Comment by john-lee-johnson** [comment]
Thank you! This works great! I hope I can bother you with a few more questions, it possible to use `geom_overlay` to make the density plots with a GS that has multiple samples? Can I use `geom_overlay` with a subset from a different GS to compare two separate experiments (which require slightly different gating parameters)? And finally, is it possible to concatenate multiple samples in a GS and plot the combined density plot?

Thank you so much for your time and help!

**Comment by mikejiang** [comment]
With the latest fix, you should be able to plot `geom_overlay` for multi-samples. 
```r
library(ggcyto)
gs <- load_gs(system.file("extdata/gs_bcell_auto/", package = "flowWorkspaceData"))
p <- ggcyto(gs, aes("Live")) + geom_density(aes(y = ..count..)) + geom_gate("Live")
p <- p + geom_overlay("CD3", fill = "lightblue",aes(y = ..count..))
```
![image](https://cloud.githubusercontent.com/assets/1385649/17110761/675295fa-5253-11e6-9c79-c3e4fcb65658.png)
And, yes,  you can **concatenate** samples by simply disabling the default `facetting` 
```r
p + facet_null()
```
![image](https://cloud.githubusercontent.com/assets/1385649/17110812/a2b51ca8-5253-11e6-8284-3818669b151f.png)

techniquely speaking, you can add any arbitrary flow data (in the form of `flowSet` or `ncdfFlowSet`) as the overlay
```r
fs <- getData(gs, "CD19")
p <- ggcyto(gs, aes("Live")) + geom_density(aes(y = ..count..)) + geom_gate("Live")
p + geom_overlay(fs, fill = "red", alpha = 0.5, aes(y = ..count..))
```
![image](https://cloud.githubusercontent.com/assets/1385649/17110974/5c924f74-5254-11e6-8982-dc66b354d7f3.png)

However, you want to make sure `sample name` from `everlay data` matches to the `flow data` in the main plot unless you don't need `facetting`.

**Comment by john-lee-johnson** [comment]
This is exactly what I was looking for, thank you so much!
